version: "2"
services:
  influxdb:
    container_name: influxdb
    image: influxdb
    ports:
      - "8086:8086"
    volumes:
      - /tig/data/influxdb:/var/lib/influxdb
      - /tig/conf/influxdb:/etc/influxdb/
    restart: always

  grafana:
    container_name: grafana
    image: grafana/grafana
    user: "0"
    ports:
      - "3000:3000"
    volumes:
      - /tig/data/grafana:/var/lib/grafana
      - /tig/log/grafana:/var/log/grafana
      - /tig/conf/grafana/grafana.ini:/etc/grafana/grafana.ini
    links:
      - influxdb
    restart: always
